CREATE DATABASE IF NOT EXISTS ISATQueue
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE ISATQueue;

CREATE TABLE IF NOT EXISTS Users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  course VARCHAR(100) NOT NULL,
  year_level INT NOT NULL,
  email VARCHAR(255) NOT NULL,
  UNIQUE KEY uq_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=x
CREATE TABLE IF NOT EXISTS Queues (
  id INT AUTO_INCREMENT PRIMARY KEY,
  service_type VARCHAR(100) NOT NULL,
  date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS QueueEntries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  queue_id INT NOT NULL,
  status VARCHAR(50) NOT NULL,
  timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_queueentries_user
    FOREIGN KEY (user_id) REFERENCES Users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_queueentries_queue
    FOREIGN KEY (queue_id) REFERENCES Queues(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  UNIQUE KEY uq_admins_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
